// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8EsQSSNxBQHYHFYfDYsZvyqE761zo370',
    appId: '1:82837744396:web:5aa1184ef5ce3dddeb3729',
    messagingSenderId: '82837744396',
    projectId: 'bible-love-hkd620',
    authDomain: 'bible-love-hkd620.firebaseapp.com',
    storageBucket: 'bible-love-hkd620.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9PU2lvQKwGlOZ_ezTDjKW7R0QnvLCNFM',
    appId: '1:82837744396:android:66b6acd84861c55feb3729',
    messagingSenderId: '82837744396',
    projectId: 'bible-love-hkd620',
    storageBucket: 'bible-love-hkd620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9OLphUaYzVpatgK1JSqXWO3ydOaK_UG0',
    appId: '1:82837744396:ios:b01d3db873e6649beb3729',
    messagingSenderId: '82837744396',
    projectId: 'bible-love-hkd620',
    storageBucket: 'bible-love-hkd620.firebasestorage.app',
    iosBundleId: 'com.example.bibleLove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9OLphUaYzVpatgK1JSqXWO3ydOaK_UG0',
    appId: '1:82837744396:ios:b01d3db873e6649beb3729',
    messagingSenderId: '82837744396',
    projectId: 'bible-love-hkd620',
    storageBucket: 'bible-love-hkd620.firebasestorage.app',
    iosBundleId: 'com.example.bibleLove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8EsQSSNxBQHYHFYfDYsZvyqE761zo370',
    appId: '1:82837744396:web:d07b92bcb7f018a3eb3729',
    messagingSenderId: '82837744396',
    projectId: 'bible-love-hkd620',
    authDomain: 'bible-love-hkd620.firebaseapp.com',
    storageBucket: 'bible-love-hkd620.firebasestorage.app',
  );

}